name: permission_toggle_button
description: A Flutter package for managing permissions with toggle buttons.
homepage: https://github.com/Mohammedfaizan2106/permission_toggle_button
repository: https://github.com/Mohammedfaizan2106/permission_toggle_button
version: 1.0.0
license: MIT

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
