name: permission_toggle_button
description: A Flutter package for managing permissions with toggle buttons.
version: 0.0.1
homepage: https://github.com/yourusername/permission_toggle_button

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
